### ISSUE TITLE
question instead of issue

### ISSUE THREAD

**Issue by firefly2000** [F5Networks/f5-openstack-heat-plugins#110]
Good day! What's the python dependency for heat-plugins: openstack redhat 7 with kilo. 

Additionally, what's the good format to ask questions like this. Thank you! - Haitao

**Comment by jputrino** [comment]
Hi Haitao! The python sdk (on which the heat plugins rely) currently only supports 2.x, but development for compatibility with python 3.x is underway. Please feel free to ask questions in the F5OpenStack slack channel going forward: https://f5openstack.slack.com/
