### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by acme58** [F5Networks/f5-openstack-heat-plugins#156]
Several links are broken on this page: http://clouddocs.f5.com/cloud/openstack/v1/heat/.

- "F5 OpenStack Heat plugins." (2 places)
- "Install the F5 Heat Plugins"

**Comment by jputrino** [comment]
@dflanigan This is a known issue, it is tracked in f5-openstack-docs [225](https://github.com/F5Networks/f5-openstack-docs/issues/225).
