### ISSUE TITLE
heat.conf plugin_dirs needs to know how to find the f5 resource files

### ISSUE THREAD

**Issue by b225ccc-zz** [F5Networks/f5-openstack-heat-plugins#3]
On Ubuntu 14, OpenStack kilo, I had to make the f5 resource files known to one of the heat plugin_dirs as part of the install.  I did this:

`ln -s /usr/local/lib/python2.7/dist-packages/f5_heat /usr/lib/heat/f5_heat`

Simply doing `pip install f5-openstack-heat-plugins` and then restarting the heat engine service was not enough.

**Comment by alonsocamaro** [comment]
Thanks! This solved it. 

For other readers it needs heat service restart but in my case ubuntu/liberty I found that heat didn't restart properly. The heat stop didn't work properly but yet it started a new instance causing the plugins to do not be properly loaded. 

Also, I had to

root@node-7:~# mkdir /var/lib/heartbeat/cores/logs
root@node-7:~# mkdir /var/lib/heartbeat/cores/logs/iControlRESTSession
root@node-7:~# chown heat:heat /var/lib/heartbeat/cores/logs/iControlRESTSession/

in my Mirantis 8.0 which installs ubuntu with Openstack liberty

**Comment by pjbreaux** [comment]
Closed by PR #18
