### ISSUE TITLE
fix line emphasis in template example

### ISSUE THREAD

**Issue by jputrino** [F5Networks/f5-openstack-heat-plugins#51]
The wrong lines are highlighted in the Sample Heat template.

http://f5-openstack-heat-plugins.readthedocs.org/en/kilo/#usage

![image](https://cloud.githubusercontent.com/assets/12143793/14504556/8fe7005a-0172-11e6-9616-99dfd8eb5471.png)

**Comment by pjbreaux** [comment]
Also fixup symlink in doc for Ubuntu installations.

ln -s /usr/local/lib/python2.7/dist-packages/f5_heat /usr/lib/heat

**Comment by dflanigan** [comment]
Fixed has been merged into kilo.  Should close was fix makes it to master

**Comment by jputrino** [comment]
Closing because issue didn't close automatically.
